### PR TITLE
Add github workflow to run black and isort on pull request

### PR DESCRIPTION
**Pull request by Kishore-abhimanyu**
Add github workflow to run black and isort on pull request

### CODE REVIEW

**Comment by extinctsion** [comment]
Hi, why isort is only running on tests? It should also rearrange the imports in methods directory as well.

**Comment by Kishore-abhimanyu** [comment]
Can you check now @extinctsion

**Comment by extinctsion** [comment]
Pls add pip install black to install and then run black.

**Comment by Kishore-abhimanyu** [comment]
Done, can you check now

**Comment by Kishore-abhimanyu** [comment]
Also, can you please add hacktoberfest label to it

**Comment by extinctsion** [comment]
There is still some errors

**Comment by extinctsion** [comment]
I'll be merging only if there are no issues. Pls look after it.

**Comment by Kishore-abhimanyu** [comment]
Can you check now? Since it is waiting for approval, i couldnt test the actual actions @extinctsion

**Review by extinctsion — APPROVED** [review]
PR approved. Thanks for your valuable contribution to the open source.

**Pull request merged**
