### PR TITLE
hacktoberfest contribution - binary to hexadecimal

### PR DESCRIPTION
**Pull request by AndrewHUNGNguyen**

### CODE REVIEW

**Comment by AndrewHUNGNguyen** [comment]
Added bin2hex function and unit tests to verify it behaves as expected.

**Comment by extinctsion** [comment]
Hi, @AndrewHUNGNguyen thanks for the contibution of testing but before that I would like to discuss with you about something. We can decide somewhere bcoz I want to understand about some of the processess we will be implementing in this  module.

**Comment by AndrewHUNGNguyen** [comment]
Hi @extinctsion, what day would work best for you? I am in PST Time Zone and work on Weekdays (8 am - 5pm my timezone).

**Comment by extinctsion** [comment]
Now? I'm kinda not busy rn.

**Comment by extinctsion** [comment]
how about 9:30pm PST that will be 11am IST for me? Does that work? If possible, u can share ur e-mail or something so that I can send you the invite link.

**Comment by extinctsion** [comment]
9:30 pm today.

**Comment by AndrewHUNGNguyen** [comment]
Hi @extinctsion. We can meet at 9:30 pm PST tonight. My email is ahn018@ucsd.edu

**Comment by extinctsion** [comment]
I shared the meet details in ur link

**Comment by extinctsion** [comment]
A reminder about the meeting

**Review by extinctsion — APPROVED** [review]

**Pull request merged**
