### PR TITLE
Graph implementation

### PR DESCRIPTION
**Pull request by Ayushlion8**
Implemented graph algorithms in an organized way.

### CODE REVIEW

**Comment by extinctsion** [comment]
Hi can you also add test cases for your PR? Add them to the folder as show in diagram in readme in main branch

**Comment by extinctsion** [comment]
pls follow this [structure] (https://user-images.githubusercontent.com/67048929/271960546-f772ba66-e2eb-4e42-b1b7-104facf6eda4.png)

**Comment by extinctsion** [comment]
pls follow this ! [structure] (https://user-images.githubusercontent.com/67048929/271960546-f772ba66-e2eb-4e42-b1b7-104facf6eda4.png)

**Comment by extinctsion** [comment]
pls follow this structure - https://user-images.githubusercontent.com/67048929/271960546-f772ba66-e2eb-4e42-b1b7-104facf6eda4.png

**Comment by Ayushlion8** [comment]
you want me to create another folder named test cases and under it I have to create sub-folder named Graph_implementation_test_cases which will contain the test cases of the graph implementation.

Am I right @extinctsion ?

**Comment by extinctsion** [comment]
yes

**Review by extinctsion — APPROVED** [review]

**Comment by Ayushlion8** [comment]
Hey @extinctsion, I have done it and raise the PR for the same please review.

**Comment by extinctsion** [comment]
Hi @Ayushlion8 , pls pull the latest master branch and then raise PR

**Pull request merged**
