### PR TITLE
Added an new function called "average"

### PR DESCRIPTION
**Pull request by arunimaChintu**
the average function is added in the easyPythonpi.py and it  finds the average of any two or three numbers.

### CODE REVIEW

**Comment by extinctsion** [comment]
Thanks for your contribution but the thing is these codes will only work for 2 inputs. whatif there are n inputs and the user have to find the avg of those n numbers? Think and resumit then ill merge it to master. Hint: use *args/*kwargs. refer google.

**Comment by arunimaChintu** [comment]
resubmitted... is it okay now?

**Comment by extinctsion** [comment]
So what does ` percentage3(x:'float', y:'float',z:'float')->'float': ` does? and why there is /2 in the code while getting percentage of three numbers. pls correct it.

**Comment by arunimaChintu** [comment]
replaced the percentage3 with calculate_percentage

**Review by extinctsion — APPROVED** [review]

**Comment by extinctsion** [comment]
This PR is reacdy to be merged.

**Pull request merged**
