### PR TITLE
Add workflow to run tests on pull request

### PR DESCRIPTION
**Pull request by Kishore-abhimanyu**
Add workflow to run tests when PR is created or updated

### CODE REVIEW

**Comment by Kishore-abhimanyu** [comment]
@extinctsion Please review the PR and let me know, if any change is required

**Comment by extinctsion** [comment]
Have you checked it on you branch? is it working? If yes, pls attach a Screenshot of the same.

**Comment by extinctsion** [comment]
Also pls configure to test for various version of python from py3.7 to latest and also on different platforms such as windows, ubuntu latest and mac.

**Comment by extinctsion** [comment]
you can take help from this youtube video - https://youtu.be/UEOtZvTCmDo?si=SwfdqnLw-3isB8P3

**Comment by Kishore-abhimanyu** [comment]
@extinctsion I have added the different python version and different os environments. Also attaching the testing evidence here
Screenshot 2023-10-22 at 5 11 12 PM

**Review by extinctsion — APPROVED** [review]
I hope it looks good and ready to be merged.

**Comment by extinctsion** [comment]
Hey @Kishore-abhimanyu can you look and tell why the test cases are not running?

**Review by extinctsion — CHANGES_REQUESTED** [review]
Line no 11. It should be  os: [ubuntu-latest, windows-latest, macos-latest]. Pls remove the extra spaces for which it is giving errors.

**Comment by Kishore-abhimanyu** [comment]
Hi @extinctsion I have fixed the space issue. As the trigger takes master branch, once the code has been merged with master, going forward for all the PR created, it should be running

**Review by extinctsion — APPROVED** [review]

**Comment by extinctsion** [comment]
Still tests are failing. We have to look after this.

**Comment by extinctsion** [comment]
Also maybe we can merge this and isort workflow together as both are doing task on pull requests? What do you think?

**Comment by Kishore-abhimanyu** [comment]
Sure we can do that @extinctsion

**Comment by extinctsion** [comment]
Still the test cases are failing.

**Review by extinctsion — APPROVED** [review]
PR approved but it will be reverted if there is any issue with PR.

**Pull request merged**
