### PR TITLE
Fix failing tests and format the files

### PR DESCRIPTION
**Pull request by Kishore-abhimanyu**
Fix failing tests and format the files

### CODE REVIEW

**Comment by Kishore-abhimanyu** [comment]
@extinctsion Please verify this PR

**Comment by extinctsion** [comment]
You are adding the binaries which are not needed. Pls add it to gitignore before raising PR

**Comment by Kishore-abhimanyu** [comment]
> You are adding the binaries which are not needed. Pls add it to gitignore before raising PR

Yes, those files are removed. It is not adding to the branch, those are removed changes. Please check

**Comment by extinctsion** [comment]
I am seeing these many files to be added, which still include binaries. Make necessary changes

**Comment by extinctsion** [comment]
Your branch is behind the main branch. Pls pull the branch, make changes then raise PR to avoid merge conflicts.

**Comment by extinctsion** [comment]
Hi @Kishore-abhimanyu  pls resolved the merge conflicts.

**Comment by extinctsion** [comment]
There are failed tests. Hence, we cannot merge this PR. Thanks for contributing in the open source community.

**Pull request closed without merging**
