### PR TITLE
Added LinkedList implementation

### PR DESCRIPTION
**Pull request by Zahid92**
Added implementation for linked list using OOP.
Against issue #50

### CODE REVIEW

**Comment by extinctsion** [comment]
pls, pull the main branch again as there is a major update in the file structure. Thank you

**Comment by Zahid92** [comment]
pulled and made changes as per new structure.

**Comment by extinctsion** [comment]
No. @Zahid92 pls follow the file structure. See, there is file in methods called linkedlist.py, you have to insert ur methods there and the test caes in the test_cases.test_linkedlist.py file

**Comment by extinctsion** [comment]
Moreover there is some error going on in the library. Pls see if you can fix it or wait. I'll let you know once it is resolved.

**Comment by extinctsion** [comment]
Please, pull the latest branch and following the standard naming conventions and file naming. thank you

**Comment by Zahid92** [comment]
@extinctsion I have also added unittest for search.
I should have raised another pull request. 
But I think with one branch only one pull request can be raised. 😅

**Comment by extinctsion** [comment]
@Zahid92 I appreciate ur hardwork. I would recommend you to pull the recent master branch and then again raise a fresh PR.

**Comment by extinctsion** [comment]
I'll attach a hacktoberfest-accepted tag to this PR. Don't worry.

**Comment by Zahid92** [comment]
> I'll attach a hacktoberfest-accepted tag to this PR. Don't worry.

@extinctsion should I close this one then raise a new PR or by creating a new branch ??

**Comment by extinctsion** [comment]
Raise new pr

**Pull request closed without merging**
