### PR TITLE
added the function bin2hex

### PR DESCRIPTION
**Pull request by IltisGraph**
this function converts a binary string into hexadecimal as mentioned in the issue #20

### CODE REVIEW

**Comment by extinctsion** [comment]
I'm very happy to see you contributing to this library. The main objective of this library was to help the python beginners to see how importing and the code is being written inside a library works. Just using inbuilt functions and returning it as output does not fulfill the cause - [return hex(int(binary, 2))]. 😂😂😂 Anyway you should try to contribute to write a method on ur own and then raise a PR. You can also ask me if u are struck somewhere. Happy to help. Happy coding.

**Comment by IltisGraph** [comment]
Hi! Actually I'm one of those beginners this repository aims for. So of course I remade the function and overall it was a very fun experience to understand how hex works.
So thank for your advice!!!

**Comment by extinctsion** [comment]
you can rewrite the method without using in-built library methods so that I can merge it with the main branch.

**Comment by IltisGraph** [comment]
@extinctsion I don't quite understand. I have rewritten the function already, what do I have to change? (Am I not allowed to use python functions like enumerate?)

**Comment by extinctsion** [comment]
@IltisGraph yes, the way you have written it now is good but the code is giving wrong output.
Moreover you can test ur input and output in this website: [Radpid Tables](https://www.rapidtables.com/convert/number/binary-to-hex.html)


Screenshot (28)

**Comment by IltisGraph** [comment]
@extinctsion I've hopefully fixed it now. I've tested it with a text function and there weren't any misstakes.

**Comment by IltisGraph** [comment]
@extinctsion but why should we give 2 as an input, if there aren't such numbers in binary? Furthermore I checked the code and on my machine there is other output than in your screenshot...
Screenshot_20230119_172232

**Comment by extinctsion** [comment]
@Jugalcody or @PreyumKr  pls look into this issue and explain why the input is clashing with the code.

**Comment by extinctsion** [comment]
@IltisGraph im sorry to say but could you pls take this latest branch and rewrite the changes acc to py 3.x documentation and re raise PR? ill close this PR as everything is jumbled up here. Waiting to see ur new PR soon.
~ from easyPythonpi team

**Pull request closed without merging**
