### PR TITLE
73 fix failing tests and format files

### PR DESCRIPTION
**Pull request by AndrewHUNGNguyen**

### CODE REVIEW

**Comment by extinctsion** [comment]
Why did test cases not run on this pull request?

**Comment by extinctsion** [comment]
Only black and isort ran on this PR

**Comment by AndrewHUNGNguyen** [comment]
I see things "Run tests on pull request / test (3.8, ubuntu-latest) (pull_request) " and "Run checks using black and isort to maintain code structure / test (3.7, ubuntu-latest)" in the all checks have passed. What could be different?

**Comment by extinctsion** [comment]
Oh wait, it was my mistake. I was checking from the app and it showed me the test only for isort and black. Rest test cases were not shown. 

I see all the tests passing now, hence merging with the main branch.

**Review by extinctsion — APPROVED** [review]
PR approved. Thanks for contributing in the open source :)

**Pull request merged**
