### PR TITLE
Added LinkedList oop implementation, tests for search and graph

### PR DESCRIPTION
**Pull request by Zahid92**
Issues addressed: #50 and #60

### CODE REVIEW

**Comment by extinctsion** [comment]
I @Zahid92 there has been few changes in the main branch. pls pull it and make necessary changes in your commit.

**Comment by Zahid92** [comment]
> I @Zahid92 there has been few changes in the main branch. pls pull it and make necessary changes in your commit.

I have pulled the latest.
After latest pull unittests are failing for multiple files including test_stringmanipulation, test_statistics, etc.
image

I see Module renaming in #65.
Am I missing something ?

**Comment by Zahid92** [comment]
@extinctsion could you review this PR ?

**Comment by extinctsion** [comment]
This branch has conflicts with the main branch. Also there are failed tests. Hence, we cannot merge this PR. Thanks for contributing in the open source community.

**Pull request closed without merging**
