### PR TITLE
Sadhiin/setup issue and github action failed

### LINKED ISSUE #92: [Issue] Improve Version Management in setup.py
# Improve Version Management in setup.py

## Current Behavior
Our current `setup.py` doesn't consistently increment the version number, which can lead to conflicts when uploading to PyPI.

## Proposed Solution
Update `setup.py` to:
1. Fetch the latest version from PyPI
2. Increment the version number automatically
3. Incorporate git information when available

This will ensure that each new build has a unique, incrementing version number that's always higher than what's on PyPI.

## Benefits
- Prevents version conflicts with PyPI
- Automates version management
- Maintains compatibility with git-based versioning
- Works in both git and non-git environments

## Implementation Details
- Add functions to fetch PyPI version and increment version
- Modify `get_version()` to use these new functions
- Ensure compatibility with existing git-based versioning

## Additional Notes
- This change will require adding `requests` to the project dependencies
- We may need to update CI/CD pipelines to accommodate this change

### PR DESCRIPTION
**Pull request by sadhiin**
# Automated Version Management for setup.py #92 

This PR addresses the issue of consistent version incrementing in our `setup.py` file.

## Changes
- Added `get_pypi_version()` function to fetch the latest version from PyPI
- Implemented `increment_version()` to properly increment version numbers
- Updated `get_version()` to use PyPI version as a base and incorporate git information
- Modified setup() to use the new versioning system

## Testing
- Tested locally with and without git tags
- Verified version increments correctly from PyPI version
- Checked compatibility with existing git-based versioning

## Notes for Reviewers
- Please check if the version incrementing logic meets our needs
- Verify that the PyPI version fetching is robust enough
- Consider any potential impacts on our CI/CD pipeline

## Dependency Changes
- Added `requests` library to project dependencies

## Related Issue
Closes #92

### CODE REVIEW

**Comment by extinctsion** [comment]
Hi @sadhiin, still the tests are failing. can you look into this issue?

**Comment by sadhiin** [comment]
> Hi @sadhiin, still the tests are failing. can you look into this issue?
Hi @extinctsion 
Yes they are! Because the updated code is not on the repo. Just manually merge them. I hope it would work fine.

**Comment by extinctsion** [comment]
Again failing test cases @sadhiin. it says 

`
File "<string>", line 6, in <module>
      ModuleNotFoundError: No module named 'requests'
      [end of output]
`

**Comment by sadhiin** [comment]
> Again failing test cases @sadhiin. it says
> 
> `File "<string>", line 6, in <module> ModuleNotFoundError: No module named 'requests' [end of output]`

On it.

**Comment by sadhiin** [comment]
> Again failing test cases @sadhiin. it says
> 
> `File "<string>", line 6, in <module> ModuleNotFoundError: No module named 'requests' [end of output]`

It's perfectly working on local
image

Let's see, things should work fine.

**Comment by sadhiin** [comment]
Hi @extinctsion please have a look no this version.

**Comment by extinctsion** [comment]
Yes it worked. Pls mention this PR in the issue so that I can or you can mark the issue as closed

**Comment by extinctsion** [comment]
Thanks @sadhiin for fixing this issue. It saved us a lot of time. Thanks again for this PR. Hopes this fixes the pipelines issue

**Comment by sadhiin** [comment]
> Thanks @sadhiin for fixing this issue. It saved us a lot of time. Thanks again for this PR. Hopes this fixes the pipelines issue

It's always fun to contribute.....! 👍🏼

**Review by extinctsion — APPROVED** [review]
I have approved on the fact that the pipelines are back to normal and giving expected results

**Pull request merged**
